# Generated by Django 6.0.8 on 2026-08-09 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=255)),
                ('involvement', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=100)),
                ('interests', models.JSONField()),
                ('challenge', models.TextField()),
                ('attend_all', models.CharField(max_length=50)),
                ('ethics_commitment', models.CharField(max_length=50)),
                ('heard_from', models.CharField(max_length=100)),
                ('refer_friends', models.CharField(max_length=50)),
                ('referral_numbers', models.TextField(blank=True)),
                ('cohort', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewing', 'Reviewing'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('waitlisted', 'Waitlisted')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('email', 'cohort')},
            },
        ),
    ]
