# Generated by Django 6.0.8 on 2026-08-12 18:05

import gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_enforce_category_and_validate_uploads'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='gallerycategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='gallerycategory',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='title',
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='year',
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to=gallery.models.gallery_image_upload_to),
        ),
    ]
